/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaTest;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        final String greeting = new App().getGreeting();
        log.info("Greeting = {}", greeting);
    }
}
